linker-v3-example:
  http:
    addr: 127.0.0.1:8800
    recovery: true
    health:
      enabled: true
      path: ping
  grpc:
    addr: 127.0.0.1:9900
  postgresql:
    host: 192.168.3.13
    port: 5432
    user: neteast
    db_name: linker_v3_example
    ssl_mode: disable
